### ISSUE TITLE
Notify if Xiaomi Gateway or some sensor is not working

### ISSUE THREAD

**Issue by vpomax** [runningman84/home-assistant-apps#5]
I found that if the Xiaomi Gateway is disconnected, the AlarmSystem will continue to work and send arming and disarming messages. But obviously, no alarm works.
First of all it should check if Xiaomi Gateway and sensors are online and otherwise send a notification message saying that AlarmSystem cannot be activated, or the alarm is activated but the xxx sensor is not active. This could be very useful

**Comment by runningman84** [comment]
It is quite difficult to find out if the system is still online within appdaemon. I would recommend you to add a feature request to home assistant because I can only work with their API if they do not expose such information I cannot handle this kind of error.

**Comment by runningman84** [comment]
A workaround might be to have a binary sensor which pings the Xiaomi device if the state goes off you could trigger an alarm. This is already possible with the current code you could just add this sensor to the motion sensor list.

**Comment by runningman84** [comment]
BTW. I would recommend to use zigbee 2mqtt if this system is offline all your sensors are marked as unavailable. Right now this state is not handled in my alarm code but it might be possible to handle it in the future.

**Comment by runningman84** [comment]
Possible solutions provided
