### ISSUE TITLE
2 or 3 booleans in 1 input_select?

### ISSUE THREAD

**Issue by sj3fk3** [runningman84/home-assistant-apps#7]
tip: instead of using different input.booleans for operation modes like "guest" or "vacation" would 1 input_select not be better? Can't really see any practical situation where both would be valid.

Cleans up code and UI/UX imho

**Comment by runningman84** [comment]
Sounds like a good idea. Feel free to create a pull request...

**Comment by sj3fk3** [comment]
I think I'm going to change more to fit my personal setup. I'll see if I can split the changes.. One more thing. I see:
`  
def count_doors_and_windows(self, state):
        count = 0
        for sensor in self._door_window_sensors:
            if self.get_state(sensor) == state:
                count = count + 1
        return count
`

But can't see where it's beging used.. Is it a unfinished feature or do I just need other glasses or really learn to code (I'm a n00b) :)
